version: '3.8'

networks:
  media_net:
    driver: bridge

services:
  plex:
    image: linuxserver/plex
    container_name: plex
    networks:
      - media_net
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/plex/config:/config
      - ${BASE_DIR}/media/tv:/tv
      - ${BASE_DIR}/media/movies:/movies
      - ${BASE_DIR}/plex/transcode:/transcode
    ports:
      - "${PORT_PLEX}:32400"              # Plex Web UI
      - "${PLEX_UDP_DLNA_PORT}:${PLEX_UDP_DLNA_PORT}/udp"       # Plex DLNA (UDP)
      - "${PLEX_UDP_BONJOUR_PORT}:${PLEX_UDP_BONJOUR_PORT}/udp" # Plex Bonjour/Avahi (UDP)
      - "${PLEX_TCP_ROKU_PORT}:${PLEX_TCP_ROKU_PORT}/tcp"       # Plex Roku Control (TCP)
      - "${PLEX_UDP_GDM_PORT1}:${PLEX_UDP_GDM_PORT1}/udp"       # Plex GDM discovery (UDP)
      - "${PLEX_UDP_GDM_PORT2}:${PLEX_UDP_GDM_PORT2}/udp"       # Plex GDM discovery (UDP)
      - "${PLEX_UDP_GDM_PORT3}:${PLEX_UDP_GDM_PORT3}/udp"       # Plex GDM discovery (UDP)
      - "${PLEX_UDP_GDM_PORT4}:${PLEX_UDP_GDM_PORT4}/udp"       # Plex GDM discovery (UDP)
      - "${PLEX_TCP_DLNA_PORT}:${PLEX_TCP_DLNA_PORT}/tcp"       # Plex DLNA (TCP)
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - media_net
    depends_on:
      - radarr
    ports:
      - "${PORT_SONARR}:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/sonarr/config:/config
      - ${BASE_DIR}/media/tv:/tv
      - ${BASE_DIR}/downloads:/downloads
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
      - media_net
    ports:
      - "${PORT_RADARR}:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/radarr/config:/config
      - ${BASE_DIR}/media/movies:/movies
      - ${BASE_DIR}/downloads:/downloads
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    networks:
      - media_net
    depends_on:
      - sonarr
      - radarr
    ports:
      - "${PORT_BAZARR}:6767"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_DIR}/bazarr/config:/config
      - ${BASE_DIR}/media/tv:/tv
      - ${BASE_DIR}/media/movies:/movies
    restart: unless-stopped

